### ISSUE TITLE
باگ در دیلیت پیام 

### ISSUE THREAD

**Issue by C4ssif3r** [AliGanji1/Pyrubi#4]
سلام اقای گنجی من داشتم کتابخونه خودم رو توسعه میدادم که متوجه شدم یسری نواقص داره
دقیقا کتابخونه شماهم همین نواقص رو داره
مثلا وقتی از متود message.delete() برای پیام هایی که حاوی گیف، عکس، ویدیو هستند استفاده میشه این اررور رو میده:

**Exception in thread Thread-17 (send_hello):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-17-a920a7efe27f>", line 9, in send_hello
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyrubi/types/socket/message.py", line 62, in reply_message_id
    return self.data["message_updates"][0]["message"].get("reply_to_message_id")
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'message'
None None



Exception in thread Thread-18 (send_hello):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-17-a920a7efe27f>", line 11, in send_hello
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyrubi/types/socket/message.py", line 172, in delete
    return self.methods.deleteMessages(objectGuid=self.object_guid, messageIds=[self.message_id], deleteForAll=delete_for_all)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyrubi/methods/methods.py", line 988, in deleteMessages
    return self.network.request(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyrubi/network/network.py", line 80, in request
    raise {
pyrubi.exceptions.InvalidInput: Some input given to the method is invalid!**


فیکس کردنش کاری نداره یه try except هست . 
مچکرم!

**Comment by C4ssif3r** [comment]
دیتای پیام فور شده:

{'chat_updates': [{'object_guid': 'u0FfLS40a81c8a72e7c10e199056adfc', 'action': 'Edit', 'chat': {'count_unseen': 12, 'time_string': '172576017800001105353581261341', 'last_message': {'message_id': '1105353581261341', 'type': 'Text', 'text': '📹  ㅤꫂ୧\nhttps://rubika.ir/joing/HAD', 'author_object_guid': 'u0FfLS40a81c8a72e7c10e199056adfc', 'is_mine': False, 'author_type': 'User', 'metadata': {'meta_data_parts': [{'from_index': 3, 'length': 72, 'type': 'Bold'}]}}, 'last_seen_peer_mid': '1105353581261341', 'status': 'Active', 'time': 1725760178, 'last_message_id': '1105353581261341'}, 'updated_parameters': ['last_message_id', 'last_message', 'status', 'time_string', 'count_unseen', 'last_seen_peer_mid', 'time'], 'timestamp': '1725760178', 'type': 'User'}], 'message_updates': [{'message_id': '1105353581261341', 'action': 'New', 'message': {'message_id': '1105353581261341', 'text': '  ꫂ୧\nhttps://rubika.ir/joing/HADIHIH0SGAWFCUPLEAVZSSVXCFOEKJ\n\u200c\u200c       𝟣𝟣﹕ @lady_rahmani  ㅤᶻ 𝘇 𐰁.', 'file_inline': {'file_id': 50729744108279, 'mime': 'mp4', 'dc_id': 878, 'access_hash_rec': '1017640614391906708301205360412024090618', 'file_name': '2_5364274665051133438.mp4', 'thumb_inline': '/9j/4AAQSkZJRgABAQAAAQABAAD/4gIoSUNDX1BST0ZJTEUAAQEAAAIYAAAAAAIQAABtbnRyUkdC\nIFhZWiAAAAAAAAAAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAA\nAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlk\nZXNjAAAA8AAAAHRyWFlaAAABZAAAABRnWFlaAAABeAAAABRiWFlaAAABjAAAABRyVFJDAAABoAAA\nAChnVFJDAAABoAAAAChiVFJDAAABoAAAACh3dHB0AAAByAAAABRjcHJ0AAAB3AAAADxtbHVjAAAA\nAAAAAAEAAAAMZW5VUwAAAFgAAAAcAHMAUgBHAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAA\nAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z3Bh\ncmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABYWVogAAAAAAAA9tYAAQAAAADT\nLW1sdWMAAAAAAAAAAQAAAAxlblVTAAAAIAAAABwARwBvAG8AZwBsAGUAIABJAG4AYwAuACAAMgAw\nADEANv/bAEMADgoLDQsJDg0MDRAPDhEWJBcWFBQWLCAhGiQ0Ljc2My4yMjpBU0Y6PU4+MjJIYklO\nVlhdXl04RWZtZVpsU1tdWf/bAEMBDxAQFhMWKhcXKlk7MjtZWVlZWVlZWVlZWVlZWVlZWVlZWVlZ\nWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWf/AABEIADIAWgMBIgACEQEDEQH/xAAbAAAABwEA\nAAAAAAAAAAAAAAAAAQIDBAUGB//EADYQAAEDAgQDBQUHBQAAAAAAAAEAAgMEEQUSITEiQWEGE1Fx\ngTKRscHRFDVSYnKy8CMmMzaC/8QAGAEBAQEBAQAAAAAAAAAAAAAAAgMBAAT/xAAdEQADAQEBAAMB\nAAAAAAAAAAAAAQIRMRIDIVEy/9oADAMBAAIRAxEAPwDKvxSvrqSaOolL42sLhwAfl3H6lCaSY2k8\nwpNG+MuMUTp3OlBaQSAMt7/LdRYjeFh6WXU9FIfJEUeyG6kyyCTkcD5nWY26S0XIHNauiwCd2ECU\nOaxrgdQdTff6I5pRYumUeGR34s56bKM6Z2bQABWWIUT6c5bXH4lWOjIWqf0yq/B9jw4abpSix3Bu\nFLGoRpYOHqCQQO6JERKwV1sUpdWlmcMcHWGjtD8UipibBV1MDDdsUz2DyDiraCHD8OnjdKeJpDml\n7gDcG/gPBVOIMIxGqMRDWOkLgANNdfmvUzwr6Gii1TJe8OsXaocROpKmyiZJhJEzP1BdEwiqD+zc\nYOUuju0gHqd/Bc0aTcWJJWxwXuoMDqpg0/aJKgsJ1uY7AjTzvr5rp6Knsia+NzmkyMiyn8Mlz7rB\nZmvpe64hseS2EmG0rqeOp1efaHEbG/RUdcwudci1jom0TllG+mmihbK9uVjttUpvshPYnVMc1lPF\nctDi+568kw08IUrRf460UiukkokMKNmhpsEo6k3lc4uO5z6lQMVpG0WKTQx6R5GFvut8QU+MR7oW\njDWBV1ZVPqKsPcSeAC56E/VXTPJU4tI0jf6mm+6lzNZBBC50ekjcwO90rB6VtfjlNTvtkf7WttBq\ndfRdBxWOM5YoqdkMMcZbwMuAPTZaFHO6IxMmZLUMd3N7lo3cPALV4VU0cr3Mo5WRCRha6KdxJuLE\nEdeW/M72VL2iheKsVBk7xkg0cBYadNh6KnAubDdHgjcsmEsLmWsIzlFtvRVlYO9IiYLlSccrJKSe\nGj7xktVlayWQbZ+drfzdLw6WGooX1DQ1gu5pPLQ2vc9NUkwtYY3EGCOXfXX6JuIuyWII8NFYCBmJ\n9oY4IrmF8oaOrBufcCVv6zCqdtM50kbCxo5jbyXePQlXk5kiV3XUVJmdkzREbaaFUhuCR4IOcF60\nXFxTi+vmna/2ovI/JBBcum1/I/2e+/qY/mHxW+xZrRUxgNFjE8kW3OiCCaJIyeIfcUH85qswcA4v\nQgi479n7gggsfTUOYm9zsWnc5xLs5Nydb3V/gw/s1p5jvCPeUEFyNopOyn+zUf8A1+wro2M/44Ry\nLhceiCCr8fCddMX2iAGSwAuTeyzLgMx05oIKd9FJ/9k=\n', 'width': 512, 'height': 288, 'time': 3000, 'size': 100515, 'type': 'Gif', 'is_round': False, 'is_spoil': False}, 'time': '1725760178', 'count_seen': '2', 'is_edited': True, 'forwarded_from': {'type_from': 'Channel', 'message_id': '1105215609711781', 'object_guid': 'c0CQwS708e050c02c7f8efeaf5eeb146'}, 'type': 'FileInlineCaption', 'author_type': 'User',

'author_object_guid': 'u0FfLS40a81c8a72e7c10e199056adfc', 'metadata': {'meta_data_parts': [{'from_index': 0, 'length': 72, 'type': 'Bold'}]}, 'allow_transcription': False}, 'updated_parameters': [], 'timestamp': '1725760178', 'prev_message_id': '1105353581225341', 'object_guid': 'u0FfLS40a81c8a72e7c10e199056adfc', 'type': 'User', 'state': '1725760118'}], 'show_notifications': [{'notification_id': 'n_u0FfLS40a81c8a72e7c10e199056adfc1105353581261341', 'type': 'Message', 'title': 'M', 'text': '📹 بازگشت \nhttps://rubika.ir/joing/HAD', 'image_file_id': 50734748208767, 'message_data': {'object_guid': 'u0FfLS40a81c8a72e7c10e199056adfc', 'object_type': 'User', 'message_id': 1105353581261341}}], 'user_guid': 'u0GwaTJ0a154c3f4417ce14304a3e397'}

**Comment by C4ssif3r** [comment]
SUMMARY ERR:

  - types/socket/message.py", line 62, in reply_message_id
    return self.data["message_updates"][0]["message"].get("reply_to_message_id")
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'message'
None None
